BIRS Python/Jupyter Notebook notes


Adding some stuff to see if GitHub's updating

More changes

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
N=5
A = 2*np.eye(N) - np.diag(np.ones(N-1),1)-np.diag(np.ones(N-1),-1)
A

array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

blah blah

more blah blah

In [4]:
B = np.array([[1,1],[1,1]])

In [5]:
B

array([[1, 1],
       [1, 1]])

In [6]:
B*B

array([[1, 1],
       [1, 1]])

Link for students to click:

https://yorku.syzygy.ca/jupyter/hub/user-redirect/git-pull?repo=https://github.com%2Fpimsmath%2Fpublic-notebooks&urlpath=tree%2Fpublic-notebooks%2Fpath%2Fto%2Ffile.ipynb&branch=master