BIRS Python/Jupyter Notebook notes


Adding some stuff to see if GitHub's updating

More changes

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
N=5
A = 2*np.eye(N) - np.diag(np.ones(N-1),1)-np.diag(np.ones(N-1),-1)
A

array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

blah blah

more blah blah

In [3]:
B = np.array([[1,1],[1,1]])

In [4]:
B

array([[1, 1],
       [1, 1]])

In [5]:
B*B

array([[1, 1],
       [1, 1]])

Link for students to click:

https://yorku.syzygy.ca/jupyter/hub/user-redirect/git-pull?repo=https://github.com/psargent19/BIRS

In [6]:
import nbgrader

ModuleNotFoundError: No module named 'nbgrader'

In [7]:
!pip install nbgrader


  Using cached nbgrader-0.7.1-py3-none-any.whl
  Using cached nbclient-0.6.6-py3-none-any.whl (71 kB)
  Using cached qtconsole-5.3.1-py3-none-any.whl (120 kB)
     |████████████████████████████████| 2.2 MB 14.1 MB/s            �██████▋        | 1.6 MB 14.1 MB/s eta 0:00:01
  Using cached nbclient-0.6.5-py3-none-any.whl (71 kB)
  Using cached nbclient-0.6.4-py3-none-any.whl (71 kB)
  Using cached nbclient-0.6.3-py3-none-any.whl (71 kB)
  Using cached nbconvert-6.5.3-py3-none-any.whl (563 kB)
  Using cached tinycss2-1.1.1-py3-none-any.whl (21 kB)
  Using cached QtPy-2.2.0-py3-none-any.whl (82 kB)
  Using cached jarowinkler-1.2.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (105 kB)
  Attempting uninstall: nbclient
    Found existing installation: nbclient 0.5.9
    Uninstalling nbclient-0.5.9:
      Successfully uninstalled nbclient-0.5.9
  Attempting uninstall: nbconvert
    Found existing installation: nbconvert 6.4.0
    Uninstalling nbconvert-6.4.0:
      Successfully uni

In [8]:
import nbgrader

In [9]:
B+B

array([[2, 2],
       [2, 2]])

In [10]:
B+B+B

array([[3, 3],
       [3, 3]])